### ISSUE TITLE
[Bug] Time-skipping to the end is still playing the current time?

### ISSUE THREAD

**Issue by NanaMizukiAnother7** [clsid2/mpc-hc#1195]
Only happens on Media Player Classic - Home Cinema version, not Black Edition version. When I skip the video's time to the end, it still plays the current time _until_ the end. What anyone else reproduce this?

The sample file I used is the Virgin Code Films Production logo from 1979.

Proof:
![MPC-HC Time-Skip Bug](https://user-images.githubusercontent.com/78664512/124408175-dc2d5980-dd6f-11eb-909a-c878d6592462.png)

Filters currently loaded:
  - Default DirectSound Device
  - MPC Video Renderer
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder (internal)
  - LAV Splitter Source (internal)

My version details (1.9.14 x64)
---------------
Build information:
    Version:            1.9.14 (4488e7d5a)
    Compiler:           MSVC v19.26.28806
    Build date:         Jul  2 2021

LAV Filters:
    LAV Splitter:       0.75.1.0
    LAV Video:          0.75.1.0
    LAV Audio:          0.75.1.0
    FFmpeg compiler:    MinGW-w64 GCC 9.3.0

Operating system:
    Name:               Windows NT 6.1 (build 7601, Service Pack 1)
    Version:            6.1 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz
    GPU:                NVIDIA GeForce 210 (driver version: 21.21.13.4201)

**Comment by lifegpc** [comment]
~hmm. Try this:
set `Options->Advanced->AllowInaccurateFastseek` to False.~
Looks like it related to DVD.

**Comment by NanaMizukiAnother7** [comment]
I just looked at latest commit that fixes the broken time-skipping to the end.

**Comment by NanaMizukiAnother7** [comment]
It's just nine days since I created this issue. How did I wait for the development release of this fixed version?

**Comment by ale5000-git** [comment]
You have to wait the new build or use the ones inside K-Lite Codec Pack 16.3.2 that is already fixed.

**Comment by NanaMizukiAnother7** [comment]
> You have to wait the new build or use the ones inside K-Lite Codec Pack 16.3.2 that is already fixed.

Alright. I will stay wait for a while.

But I don't use K-Lite Codec Pack because it will conflict my other codecs that make the videos unplayable. I installed separate codecs and media players for better playback.

**Comment by ale5000-git** [comment]
You can alternatively:
1) Install it on another pc and just copy mpc-hc64.exe on your main pc
2) or install it deselecting all codecs (I have never tried this)
3) or directly extract the mpc-hc64.exe file from the installer with [innounp](http://innounp.sourceforge.net/)

**Comment by clsid2** [comment]
What conflict? It seems to me you are blaming it for something you did wrong yourself.

**Comment by NanaMizukiAnother7** [comment]
> What conflict? It seems to me you are blaming it for something you did wrong yourself.

K-Lite Codec Pack. I neither conflict nor install it.

Also, this bug isn't fixed yet on version 1.9.14.14...

**Comment by clsid2** [comment]
Upload the sample file.

**Comment by NanaMizukiAnother7** [comment]
[Indian Logo - MPC-HC Bug.zip](https://github.com/clsid2/mpc-hc/files/6843267/Indian.Logo.-.MPC-HC.Bug.zip) I uploaded it!

**Comment by clsid2** [comment]
Should work a little bit better in 1.9.14.18
A seeking improvement in LAV Splitter is needed to make it work 100% good. Currently repeat may fail to work.

**Comment by NanaMizukiAnother7** [comment]
It works little bit.

**Comment by NanaMizukiAnother7** [comment]
It seems that this is not a MPC-HC bug. It's a bug on LAV Splitter! It does not happen on AV Splitter.

Also, I reproduced here on PotPlayer.
