### ISSUE TITLE
Latest MPC does not work in Win11

### ISSUE THREAD

**Issue by banjer12** [clsid2/mpc-hc#1662]
Latest nightly builds dont work in Win11.
Versions 46 and 52 , not possible to set your files inside the program (MPC) .
Not possible to remove a file or to put it up or down into the menu. ( Favorites-menu )

Had to go back two times to the 36-version , which works fine !

**Comment by clsid2** [comment]
@adipose
Organize Favorites shows empty list in classic theme.
Buttons also not working in both themes, but that was already known bug.

Not specific to Windows version.

**Comment by adipose** [comment]
I see both issues--reviewing.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1663

**Comment by adipose** [comment]
Fixed the classic theme bug.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1664

Fix button problem.

**Comment by xLn2** [comment]
additionaly I found another possible glitch, 
open a video and play
organize favorites
while playing video bring mouse on a favorite item
tooltip shows up back of the organize favorites window and media player window.
![resim](https://user-images.githubusercontent.com/3073922/162865090-089e438d-dd26-49d2-81cb-8a5003129a20.png)

it happens when media is at playing state. 
Thank you for your great effort.

**Comment by adipose** [comment]
Fixed the issue where adding favorites from main dialog didn't reflect in the organize dialog.  Fixed a tooltip issue.

**Comment by adipose** [comment]
I could replicate the tooltip issue by enabling always on top.  I guess there's some problem with the parent Z order when on-top is set.  Even thought it's "on top," the dialog is still not behind the player...

**Comment by adipose** [comment]
Committed a fix for that too, now.

**Comment by banjer12** [comment]
Just tried latest 52-version again , after you said its been fixed .............
Well , its still not fixed !!@@!!    ( Committed a fix for that too, now. ) ???
I wont install these "nightly builds " anymore , cost me lots of time and have to go back to working version everytime !

**Comment by xLn2** [comment]
> Just tried latest 52-version again , after you said its been fixed .............
> Well , its still not fixed !!@@!! 
> I wont install these "nightly builds " anymore , cost me lots of time and have to go back to working version everytime ! 

If someone called it is fixed you should look next developer version and be calm because its GNU licence and no gives any warranty. People here are not payed, but interest this project by their own will and cost their free time. If you want to stable build go release page and download it. Yelling to people is not good way to respect their work. Adipose almost renewed organize favorite part of software and trying to it less glitchy.

“Insanity is doing the same thing over and over and expecting different results.”

**Comment by banjer12** [comment]
Sorry , I dont want to be rude !
But tried latest nightly many times with no effort , wont do this anymore !
Thank you !

**Comment by ale5000-git** [comment]
@banjer12: "Tried"... you just need to download the zip and run it without override the installed version.

**Comment by clsid2** [comment]
The new fixes are not present in a two day old dev build. Time travel does not yet exist.
