### ISSUE TITLE
Clicking on Windows 11 notifications from Chrome sometimes opens MPC-HQ save image dialog

### ISSUE THREAD

**Issue by lastmetroid** [clsid2/mpc-hc#2204]
I know this sounds crazy and I have no idea how this is possible, but there is a bug since over a year or so if you use MPC-HQ in Windows 11. Not sure how you can trigger this bug it seems to happen random.

I notice this bug because I have often a view instances of MPC-HQ running where I save frame-capture screenshots via the file => save image. Then I let the videos open in the background.

Then when I get random notifications from Chrome, for example about a new Youtube subscription and I click the "open link" from the Windows 11 Chrome notification, it doesnt open the Link in Chrome, it opens the last "save as" dialog, which I used some moments / hours before in the MPC instance, which is still opened in the background, where I saved a image.

**Comment by clsid2** [comment]
I can't fix bugs in Windows.

Disable this option:
Options > Player > Keys > Global Media Keys
It is known bug in Win10/11 that it sometimes sends unwanted play/pause command. Maybe a similar issue with your problem.

**Comment by lastmetroid** [comment]
That option was never activated just checked and it is disabled.

**Comment by adipose** [comment]
> I know this sounds crazy and I have no idea how this is possible, but there is a bug since over a year or so if you use MPC-HQ in Windows 11. Not sure how you can trigger this bug it seems to happen random.
> 
> I notice this bug because I have often a view instances of MPC-HQ running where I save frame-capture screenshots via the file => save image. Then I let the videos open in the background.
> 
> Then when I get random notifications from Chrome, for example about a new Youtube subscription and I click the "open link" from the Windows 11 Chrome notification, it doesn't open the Link in Chrome, it opens the last "save as" dialog, which I used some moments / hours before in the MPC instance, which is still opened in the background, where I saved a image.

In Windows, the "last folder" opened in "file save/open" is reused from application to application.  Unless--the application (as MPC-HC does) goes out of its way to remember the last folder opened.  Chrome may not be saving its last folder opened.

MPC-HC will remember, but it probably also updates the last folder used, just because that's what windows API does.

**Comment by lastmetroid** [comment]
@adipose This issue is, that if you have MPC open in systray for example, and click on Windows 11 Chrome notification for example a new video on YT, the button in the notification should open Chrome YT link, but when you click the button, it opens save screenshot dialog from the running MPC instance.

**Comment by adipose** [comment]
> @adipose This issue is, that if you have MPC open in systray for example, and click on Windows 11 Chrome notification for example a new video on YT, the button in the notification should open Chrome YT link, but when you click the button, it opens save screenshot dialog from the running MPC instance.

Can you explain more how you start mpc-hc and run it in the background?

**Comment by lastmetroid** [comment]
@adipose just open it with a video so a video is loaded in MPC, paused, and keep it minimized or in systray, then let chrome trigger a notification, sooner or later when clicking on the notification of Windows, it opens save screenshot of mpc of the loaded video instead of chrome url

**Comment by adipose** [comment]
OK, I have tried to reproduce it, but so far it never happened.

**Comment by lastmetroid** [comment]
no it cant be reproduced with 100% chance

**Comment by adipose** [comment]
Are you using F5 or Alt+I or File+Save image?

**Comment by lastmetroid** [comment]
yes you need also save a few images before I guess via file save image

**Comment by xLn2** [comment]
I have something similar bug. When I click windows notifications which is downloaded file by chromium based browser , it cause to play media.

I changed Global media keys 'on' saved and later again changed to 'off' and my problem is solved.

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/c4a19ee1-d2ec-4701-a597-610e04cc67b9)

Save image does not appear to have a global app command.  _Play_ does, and I can reproduce that--notifications consistently are sending out the APPCOMMAND_MEDIA_PLAY command.  Perhaps the idea is that the popped up browser/etc. may have a media to play, and this is meant to trigger it.

**Comment by clsid2** [comment]
That is a long known bad behavior of Windows and the reason why Global Media Keys is turned off by default.

Maybe the values in wParam/lParam can help identify it is an unwanted action. But I think I already tried that once.

**Comment by lastmetroid** [comment]
Like I already said above, global media keys is turned off in MPC settings, it still happens. The issue with it opening save image dialog might be a different issue than trigger play media.

![image](https://github.com/clsid2/mpc-hc/assets/6721083/d15ba923-88e3-4a7b-9c31-84e8520a9119)

is off, still happening

**Comment by clsid2** [comment]
We were talking about the issue mentioned by xLn2.

**Comment by clsid2** [comment]
Try changing/removing the Save Image keyboard shortcuts in MPC-HC.

**Comment by adipose** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3324395/626729cd-4732-426f-974a-5a0a1d679fc2)
![image](https://github.com/clsid2/mpc-hc/assets/3324395/3a23addb-f026-40d6-b50d-8d59360144fc)

I could reproduce the problem now, but only by setting the appcommand and then turning on global media.

**Comment by lastmetroid** [comment]
Maybe there is some underlying issue where global media keys are still activated and default/off is ignored, by a special ways mpc is launched and then is active for this instance and not the next time mpc is launched normally idk

**Comment by adipose** [comment]
> Maybe there is some underlying issue where global media keys are still activated and default/off is ignored, by a special ways mpc is launched and then is active for this instance and not the next time mpc is launched normally idk

It's possible, I guess.  But can you confirm whether you have the "app command" set for "save image" in Keys?

**Comment by lastmetroid** [comment]
No. was never edited/on

![image](https://github.com/clsid2/mpc-hc/assets/6721083/83ea72ef-a11d-4899-bbd1-952e3abb52bd)

**Comment by clsid2** [comment]
Test with Alt+I and F5 key combos removed.

**Comment by lastmetroid** [comment]
I removed alt+i and f5 bindings, they were still set it seems. I have no idea how they could be triggered though when pressing the windows notification.

**Comment by clsid2** [comment]
Restart the player after making changes.

**Comment by lastmetroid** [comment]
I will test over the next weeks if this fixes it. Yes I already noticed that if you have multiple instances of MPC open the last one you closes overwrites the settings.

**Comment by lastmetroid** [comment]
Issue still happens, I just noticed it again cliking on "dismiss" button from the Windows 11 Chrome twitter notification having a MPC instance open and every time I click dismiss it opens "save a copy" from MPC. save a copy has no key bound in mpc settings. it also seems to just happen if mpc window is in front not minimized. If another window is in front of mpc it also doesnt happen.
