### ISSUE TITLE
Access Violation Crash on MPC Video Renderer

### ISSUE THREAD

**Issue by ralinchan** [clsid2/mpc-hc#2622]
Currently on MPC-HC64 v2.1.6 (4a9c40908)

Appears to be a repeat of #1792 

Only appears to happen on MPC Video Renderer. Tested MadVR and doesn't appear to crash.

WinCrashReport gives me:
Exception Description: Access Violation - Failed to access 00000000`1BF3B168 memory address (Read Access)
Exception Code: C0000005

Windows Error report appears to give exception code c000041d

**Comment by clsid2** [comment]
Use the MPC Video Renderer from MPC-HC download page.

Give link to the video file.

**Comment by ralinchan** [comment]
Should I be trying 2195 or 2203

https://subsplease.org/shows/sousou-no-frieren/

Ep25, 1080p

Can't link a torrent off nyaa so also appears to occur with ASW's release of Wrong Way To Use Healing Magic (Chiyu Mahou no Machigatta Tsukaikata)

**Comment by clsid2** [comment]
[2203](https://github.com/clsid2/mpc-hc/releases/download/2.1.6/MPCVideoRenderer_0.7.2.2203.zip)

Is there a specific timestamp where the crash occurs? It seems to play fine here.

Doesn't MPC-HC itself show crash message?

Exception code c000041d means "An unhandled exception was encountered during a user callback."
So possibly a driver issue.

**Comment by xLn2** [comment]
![image](https://github.com/clsid2/mpc-hc/assets/3073922/893f1905-b281-4133-8773-9153e1e6ecca)

Maybe not related, but it can be triggered by running at the same time with JRiver player. In my own case, there may be a slight correlation with exporting and re-importing the settings. Or if both k-lite codec and mpc-hc are installed separately in the system, it can give an error. A clean install with the k-lite codec solved the problem for me.

**Comment by clsid2** [comment]
Can you trigger it with separate MPC-HC (portable) install that includes the DrDump crash reporter? That gives a crash report that is actually usable.

Is JRiver also using MPCVR in your config?

Does the crash occur directly when opening file, or when closing, or during playback?

**Comment by xLn2** [comment]
It was 2 weeks before and probably Mpc-hc standalone installed, also K-lite codec pack standart release with mpchc, J river 31 with standart settings, mini audio player mode and audio is paused. While I was using k-lite included mpc-hc, when I double click or right click at fullscreen during playback video, it mostly crashed and also random crashes happened.

**Comment by clsid2** [comment]
If it ever happens again, grab the portable zip and try to generate a DrDump crash dump.

**Comment by ralinchan** [comment]
> [2203](https://github.com/clsid2/mpc-hc/releases/download/2.1.6/MPCVideoRenderer_0.7.2.2203.zip)
> 
> Is there a specific timestamp where the crash occurs? It seems to play fine here.
> 
> Doesn't MPC-HC itself show crash message?
> 
> Exception code c000041d means "An unhandled exception was encountered during a user callback." So possibly a driver issue.

There is no specific time stamp that it occurs.

To get it to occur for me, I open MPC and set the renderer back to MPC Video Renderer. Then I open the video file (to be consistent I used the Frieren episode again) and have it begin playing. I maximize the video player to full screen. Double click it to make it return to non-full screen size and it will immediately crash. I can do it right as the file starts playing or I can skip to a random point in the video and perform the full screen then double click restore and it will crash.

I lean towards it not being a driver specific issue since I did not change my driver and did not experience this issue earlier in the week when I was using MPC v2.1.3. The only change I made was updating MPC.

Edit: Tested with 2203. Still crashes. For completion, I downloaded 2.1.3 and downgraded. Does not crash.

**Comment by clsid2** [comment]
Can you try versions in between 2.1.3 and 2.1.6? If you can pinpoint when it started, that would make it easier to investigate what is wrong.
Enable the Crash Reporter if you disabled that in settings.

**Comment by ralinchan** [comment]
> Can you try versions in between 2.1.3 and 2.1.6? If you can pinpoint when it started, that would make it easier to investigate what is wrong. Enable the Crash Reporter if you disabled that in settings.

Done. Starts crashing on 2.1.5. I assume it's automatically sent as there doesn't seem to be an option to copy the DrDump output.

Edit: Seem to be able to make it crash on 2.1.4 also. I may not have noticed it since out of habit I switch to MadVR before playing the first file.

**Comment by clsid2** [comment]
It usually opens webpage on drdump.com with details. Copy that link here if it does.

**Comment by ralinchan** [comment]
> It usually opens webpage on drdump.com with details. Copy that link here if it does.

2.1.6 - https://drdump.com/UploadedReport.aspx?DumpID=127685627
2.1.5 - https://drdump.com/UploadedReport.aspx?DumpID=127685630
2.1.4 - https://drdump.com/UploadedReport.aspx?DumpID=127685658

Tangentially related, who's it uploading it to when it says thanks for sending the crash report if it's not going to you?

**Comment by clsid2** [comment]
That is related to the libass option. Not the video renderer.

Are you using any Pan&Scan adjustments or non-standard view settings?

I reproduced this crash once when stretching video where subtitle was located outside of visible area. That was fixed in 2.1.6 but maybe a similar issue still exists.

**Comment by ralinchan** [comment]
> Are you using any Pan&Scan adjustments or non-standard view settings?

I don't think so. The only settings i've changed is whether or not it keeps file history/remember last position, swapping renderer between MPC and MadVR, and sometimes using the "Touch window from inside" option. For this playback, I used standard normal size and expanded it to full screen.

Since you mentioned subtitle, I had an idea that it might be related to K-Lite Codec Pack which I use so I reverted to an older version (18.0,5, 2 releases back) of the codec pack and from what I can tell, 2.1.6 doesn't crash so I think we can assume that there's an issue with KLite's 18.1.5 release (which from what I see, bundles 2.1.6). Though according to their changelog, the libass option was present since 18.0.0 and no changelog mentions of it afterwards.

**Comment by clsid2** [comment]
"Touch Window From Inside" is the default and recommended setting.

I have triggered the crash once with Normal size. I will investigate it further.

**Comment by clsid2** [comment]
I think it is fixed now. Try this version:
https://github.com/clsid2/mpc-hc/releases/download/2.1.6/MPC-HC.2.1.6.8.x64.zip

**Comment by ralinchan** [comment]
Just tested it and tried to force a crash including spamming resizing. Looks like its fixed! Thank you!

**Comment by clsid2** [comment]
Great.

As a tip, Alt+1/2/3 is a much easier way to resize video to 50/100/200% than changing video frame setting.
