### ISSUE TITLE
2 issues of seekbar video preview.

### ISSUE THREAD

**Issue by Max33Verstappen** [clsid2/mpc-hc#2692]
1. Previews on some files are blank (actually they were shown briefly and then became blank.). I must move the mouse a bit to trigger a different frame to show again. [Example File](https://www.sendspace.com/file/i2q784)
![2024-03-28_02 34 11 906_mpc-hc64_preview_test mkv](https://github.com/clsid2/mpc-hc/assets/97274607/28c534a8-de73-44b5-9005-a7a6a482bf98)
2. If I leave the preview window open and press "ctrl+c" to close the video, the preview window gets stuck on.
![2024-03-27_22 10 07 953_mpc-hc64_Media_Player_Classic_Home_Cinema](https://github.com/clsid2/mpc-hc/assets/97274607/46157cc2-9aa2-4c79-a66b-2ea81144bcb6)

**Comment by clsid2** [comment]
1. Not a bug. Video simply contains some black keyframes.
2. Bug.

**Comment by Max33Verstappen** [comment]
About the 1st issue:
Do you mean *black* frames? But they have an icon at the center:
![2024-03-28_02 34 11 906_mpc-hc64_preview_test mkv1](https://github.com/clsid2/mpc-hc/assets/97274607/c8518bee-364e-4e82-adfe-88421775e1ee)
And the example video I uploaded has almost every frame mouse pointed on blank.  I also tested with MPC-BE and Potplayer and they don't present such an issue.

**Comment by clsid2** [comment]
Works fine here with newer LAV Filters, so will be solved on next update.

**Comment by clsid2** [comment]
Fixed

**Comment by Max33Verstappen** [comment]
The 1st issue seems to relate to the GPU used. When playing **certain files**(Low Res, Low Bitrate I guess. Like the one I posted), the issue is very severe on a PC using an ancient GTX 970. And it's less severe but still happens quite a lot on a laptop with mx150(also fairly aging). And I **don't** observe this issue on a modern PC with an INTEL UHD Graphics 730.
Some files (High res and high bitrate) can barely trigger this issue (Still encountered sometimes but very rare).
I made a [screen recording](https://www.sendspace.com/file/4fxwto) representing this issue on a PC with GTX 970.  You can see this issue only happens on the initial frame the mouse points to, and if I **slide** it to other frames, they're rendered just fine.
It looks like relating to the internal LAV filter? because I don't observe such an issue on MPC-BE and PotPlayer.

**Comment by clsid2** [comment]
Preview does not use hardware acceleration, so GPU should not matter much.

I can not reproduce any problem, so I can not fix it.
