### ISSUE TITLE
Incorrect libass rendering?

### ISSUE THREAD

**Issue by Kered13** [clsid2/mpc-hc#2914]
I'm trying to use the internal subtitle filter with libass and I'm getting these strange results:

![EMBER  Dungeon Meshi - 01 mkv_snapshot_11 31 186 broken](https://github.com/clsid2/mpc-hc/assets/21075688/7ef6a0c0-99e9-447d-a4c3-9709fd3060e9)

For comparison, here is what it is supposed to look like:

![image](https://github.com/clsid2/mpc-hc/assets/21075688/edb1219a-ebc6-4344-9a9b-42a8d3351392)

This was captured using [xy-VSFilter with libass](https://github.com/Masaiki/xy-VSFilter). VLC also produces the same output.

For completeness, here is the image using the internal subtitle filter *without* libass:

![EMBER  Dungeon Meshi - 01 mkv_snapshot_11 31 186 broken 2](https://github.com/clsid2/mpc-hc/assets/21075688/5874e606-a5bf-4777-ba6a-11cf0a006a17)

I know nothing about subtitle rendering (or video players in general), so I have no idea what is going on, and I cannot rule out user error, but I tried my best to make sure I was using it correctly.

The video file can be found [here](https://nyaa.si/view/1763052) using the Kagiriari subtitle track.

**Comment by clsid2** [comment]
Rendering correct here.

Try with 2.3.2.19

**Comment by xLn2** [comment]
The issue is probably related to Saving Image features of MPCHC.

MPC-Video Renderer
Timestamp: 11:31.000
With ISR, Save Image output
![EMBER  Dungeon Meshi - 01_snapshot_11 31 000](https://github.com/clsid2/mpc-hc/assets/3073922/86c57d36-b48d-4cd6-b4cb-434215c8ec30)

With ISR+Libass, Save Image output
![EMBER  Dungeon Meshi - 01_snapshot_11 31 000libass](https://github.com/clsid2/mpc-hc/assets/3073922/7a9d4a67-1c70-44bd-95e7-ed5ab714a958)


Screen recording with sharex, ISR 
![mpc-hc64_ISR](https://github.com/clsid2/mpc-hc/assets/3073922/6044160f-f357-4089-bb8d-0cee18df38a5)

Screen recording with sharex, ISR+libass
![mpc-hc64_libass](https://github.com/clsid2/mpc-hc/assets/3073922/f1b4b36c-c0c5-4dc7-822f-847d202f573b)

**Comment by clsid2** [comment]
That is some different issue.

The font issue is already fixed by latest libass update.

**Comment by Kered13** [comment]
This is **not** an issue with screenshots, I have changed the title back. If the rendering had only been broken with screenshots, I would have said so.

@clsid2 Thank you for your reply. I tried downloading 2.3.2.19, but the rendering is still broken. It is the same as in my first screenshot above. Interesting that it is working for you. Is there any information I can provide to help you investigate this issue further?

Here are my laptop specs:

* Windows 10
* Core i5-10210U
* integrated graphics
* 8 GB RAM

Here is my Help > About:

```
MPC-HC (64-bit)
---------------

Build information:
    Version:            2.3.2.19 (6a06f6e64)
    Build date:         Jul 10 2024

LAV Filters:
    LAV Splitter:       0.79.2.18
    LAV Video:          0.79.2.18
    LAV Audio:          0.79.2.18
    FFmpeg compiler:    MinGW-w64 GCC 13.3.0

Operating system:
    Name:               Windows 10 (Build 22H2)
    Version:            10.0.19045 (64-bit)

Hardware:
    CPU:                Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    GPU:                Intel(R) UHD Graphics (driver version: 27.20.100.8984)
    Monitor:            \\.\DISPLAY1 - Generic PnP Monitor [1920x1080 32-bit 120 DPI] - [Current]

Text:
    Scale Factor:       1.000000
    Ansi Codepage:      65001
```

**Comment by clsid2** [comment]
Maybe you enabled forcing of default style.

**Comment by Kered13** [comment]
Thank you, I can confirm that was the issue. I looked all over the options for it and couldn't find the force option, before realizing it was in the Play menu. I'm not sure when or how that got enabled.

**Comment by NBruderman** [comment]
Should I open a different issue for the screenshots with subs problem? Or was it resolved?

**Comment by clsid2** [comment]
No. I am not going to fix that one.
