### ISSUE TITLE
Can not save subtitle

### ISSUE THREAD

**Issue by JackJazzTV** [clsid2/mpc-hc#3353]
I am downloading subtitles for my vietnamese wife, when we watch films.

I start the film and load the subtitle, but they are almost allways out of sync.

I use the brilliant sync tool in MPC-HC, and then I save the subtitle - ready for when we have time to watch the film.

This always worked perfect, but after MPC-HC v2.0.0 it doesn't work anymore. When I choose to save subtitle, nothing happens at all.

I am forced to continue using v1.9.24, but I would like the problem fixed, so I can update to the latest version.

**Comment by clsid2** [comment]
Menu > File > Subtitles > Save Subtitle
Is working normally here for external SRT subtitle file, and also with a downloaded subtitle.

Try these development builds to further narrow down when problem started:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.24.8

**Comment by clsid2** [comment]
Are you perhaps playing a DVD instead of a file?

**Comment by clsid2** [comment]
Should be fixed now

**Comment by JackJazzTV** [comment]
Thanks for the answer.

> Menu > File > Subtitles > Save Subtitle Is working normally here for external SRT subtitle file, and also with a downloaded subtitle.
> 
> Try these development builds to further narrow down when problem started: https://github.com/clsid2/mpc-hc/releases/tag/1.9.24.8

Yes, I am plaing the movie and then loading the subtitle (SRT) in Menu > File > Subtitles > Load subtitle
And then I adjust the subtitle using CTRL+6.
And the nothing happens when I use Menu > File > Subtitles > Save Subtitle

I tried the builds, and it's working on 1.9.24.18.x64.

**Comment by JackJazzTV** [comment]
Thanks for the answer

> Are you perhaps playing a DVD instead of a file?

Sometimes I play DVD, and sometimes I play files, but the problem is with the downloaded subtitles.

I download SRT and then I load the subtitle when playing the film, and then I adjust and when i try to save using "Menu > File > Subtitles > Save Subtitle", then nothing happens at all.

I did this for a very long time, and it always worked fine, but after v1.9.24 it stopped working.

I have not changed anything in my setup.

**Comment by JackJazzTV** [comment]
Thanks for the reply.

> Should be fixed now

I downloaded the latest v2.4.2.x64 and it still doesn't work.

**Comment by JackJazzTV** [comment]
OOps.. I have more to this answer...

> Thanks for the answer.
> 
> > Menu > File > Subtitles > Save Subtitle Is working normally here for external SRT subtitle file, and also with a downloaded subtitle.
> > Try these development builds to further narrow down when problem started: https://github.com/clsid2/mpc-hc/releases/tag/1.9.24.8
> 
> Yes, I am plaing the movie and then loading the subtitle (SRT) in Menu > File > Subtitles > Load subtitle And then I adjust the subtitle using CTRL+6. And the nothing happens when I use Menu > File > Subtitles > Save Subtitle
> 
> I tried the builds, and it's working on 1.9.24.18.x64.

I continued testing:
The only one on the page working is v1.9.24.18x64.

I tested these, that are not working:
1.9.24.27.x64 and 1.9.24.31.x64 and 1.9.24.38.x64 and 1.9.24.51.x64.

**Comment by clsid2** [comment]
2.4.2 is two weeks old. Why do stupid people keep believing in time travel...
