### ISSUE TITLE
infinite opening... and stop button not working bug

### ISSUE THREAD

**Issue by wadawada** [clsid2/mpc-hc#604]
test link:
https://tv.youkutv.cc/2020/01/10/y5CXTremnwG51jFb/playlist.m3u8
https://zuikzy.win7i.com/2020/01/10/M1iMrBwFLnvIgVFl/playlist.m3u8

also can you enable stop button at all times?
opening certain files always freeze the program with no way to stop it

**Comment by clsid2** [comment]
Already fixed in latest development build:
https://github.com/clsid2/mpc-hc/releases

**Comment by wadawada** [comment]
I have installed the latest dev build but it does not seem to solve the problem
It's still opening infintely
Here is another test link
https://zk.sd-dykj.com/2020/07/30/6PRpYeQSzfWTcpp4/playlist.m3u8

**Comment by clsid2** [comment]
You must copy/paste the url in the player.
Menu > File  > Open File/URL

Clicking on the link en then opening the m3u8 file does not work. It needs to know the source of the playlist.

**Comment by wadawada** [comment]
I do and I have figured something
I have been using latest k-lite with mpc and I installed dev build to replace the mpc
installed mpc can't play test link 1 and 2

Then I download dev build zip. It can play test link 2, but unstable
If I click somewhere on progress bar, it may not play smoothly
And it still does not play test link 1(infinite opening)
When I click close, and then exit the program safely, Lock Hunter shows that mpc-hc64.exe is still locking
Although I can't find it in task manager, but it will be released after some time
I have to make sure it is released otherwise it can't play test link 2 again

Then I use vlc to test
it can play both test link 1 and 2 very smoothly when I click somewhere on progress bar

test link 1:
https://tv.youkutv.cc/2020/01/10/y5CXTremnwG51jFb/playlist.m3u8
test link2:
https://zk.sd-dykj.com/2020/07/30/6PRpYeQSzfWTcpp4/playlist.m3u8

**Comment by clsid2** [comment]
All those links work here with K-Lite 15.7.1:
http://codecguide.com/klcp_beta.htm

The smoothness issue is not fault of player. That needs to be fixed in LAV Filters.

**Comment by wadawada** [comment]
ok I spent a lot of time testing these versions and figured something
I downloaded 1.97.34 zip on github and 1.97.40 which is included in k-lite
and I almost can't play link2 on .40 but I can sometimes play link2 on .34

I can only play link2 on .34 sometimes, meaning I can probably play it immediately after I unzipped it
After I play it one time, something may be altered or something related to file being lock and It's 50/50 whether if I can play link2 the second time after I closed and reopened .34
I have to delete the .34 zip folder and re-unzip it again in order to maybe play it successfully
(and .34 folder is locked sometimes even the program is closed so I will have to wait a few seconds/minutes to delete the folder)

I can't usually play link2 on .40, however there is an exception, and this is only consistent result that I get
the condition is if I get to play link2 on .34, then I can close file on .34/or not and immediately play link2 on .40 and it can open file and play. Otherwise .40 always get infinite opening link2/link1 by itself

there are cases that I can occasionally play link1 on either .34 or .40, but I can't produce a consistent condition so it is random
