### ISSUE TITLE
Problem with subtitles in version 1.9.9x64

### ISSUE THREAD

**Issue by NEKolev** [clsid2/mpc-hc#884]
After installing 1.9.9x64 of 1.9.8x64, the subtitles are not displayed correctly. In version 1.9.8 there were no problems with playback, I did not change anything except the update to 1.9.9. In the attached archive is the subtitle file.

![1boD45dbYb](https://user-images.githubusercontent.com/70388317/107437488-c35da680-6b37-11eb-9147-a3823f84a79f.jpg)
[SUB.zip](https://github.com/clsid2/mpc-hc/files/5954656/SUB.zip)

**Comment by lifegpc** [comment]
Can u try this [test build](https://mega.nz/file/t9gEmaqD#42A5PVIlr0zCGnbphFtDldUcZ7iPKaLiYSvG2S8KW4I). #871

**Comment by clsid2** [comment]
Test if the previous development build still worked ok:
https://github.com/clsid2/mpc-hc/releases/download/1.9.8.26/MPC-HC.1.9.8.159.x64.exe

Which language is that subtitle?
It shows weird characters here even with 1.9.8 and also in a text editor. So it probably only display correctly with a certain code page.

**Comment by lifegpc** [comment]
![image](https://user-images.githubusercontent.com/41434272/107445781-135c5d80-6b78-11eb-9a12-9c181a560dfb.png)
Notepad++ works fine.

**Comment by clsid2** [comment]
This should fix it:
Options > Subtitles > Default Style > change Default (1) to Russian (204)

**Comment by Srandista** [comment]
I have the same issue, some characters from Czech subtitles aren't shown correctly.

Last development version seems to be showing them correctly.

**Comment by Srandista** [comment]
Attaching screenshot and subtitles:
![Subtitles_MPC_199](https://user-images.githubusercontent.com/5399824/107505210-a5765d00-6b9c-11eb-9858-9f0116214eb7.png)
[Subtitles.zip](https://github.com/clsid2/mpc-hc/files/5957845/Subtitles.zip)

**Comment by clsid2** [comment]
I will fix this soon.

But as a workaround you can set the correct code page in the subtitle settings, as mentioned above. In your case needed value is not RUSSIAN but probably EASTEUROPE.

**Comment by NEKolev** [comment]
@clsid2 I have this encoding, but the problem is not fixed. Language is Bulgarian.
![Yw5ZuF5RBY](https://user-images.githubusercontent.com/70388317/107538287-78da3980-6bcc-11eb-9ce3-9fb342fb22a2.jpg)

**Comment by clsid2** [comment]
Try 1.9.9.1 development build

**Comment by Srandista** [comment]
New dev build works fine as well (at least on my side).

**Comment by clsid2** [comment]
Good. I will leave this issue open to avoid duplicate reports. I might make a new release soon, after we get some more stuff committed.

**Comment by NEKolev** [comment]
@clsid2 Yes, with 1.9.9.1 no problem.

**Comment by ghost** [comment]
Same problem with Turkish subtitles, Turkish characters (ş,ğ,ü,ı,ö)


![Ekran Görüntüsü (197)](https://user-images.githubusercontent.com/78983186/107819961-10858680-6d8b-11eb-9503-0c2ef46af185.png)
![Ekran Görüntüsü (198)](https://user-images.githubusercontent.com/78983186/107819963-111e1d00-6d8b-11eb-8ed2-d20662bc0315.png)
![Ekran Görüntüsü (199)](https://user-images.githubusercontent.com/78983186/107819964-11b6b380-6d8b-11eb-9593-277a7c1d42ad.png)
![Ekran Görüntüsü (200)](https://user-images.githubusercontent.com/78983186/107819956-0f545980-6d8b-11eb-82ea-0e56ddeb9b59.png)

**Comment by NEKolev** [comment]
@keremsezen try with dev verison 1.9.9.1,

**Comment by ChepOd** [comment]
Hi,
croatian subtitles also have strange characters only in 1.9.9 x64 ver. No matter what option select, it can't be corrected.

**Comment by clsid2** [comment]
It is fixed in the development builds:
https://github.com/clsid2/mpc-hc/releases/tag/1.9.9.1
